---
# tasks file for prometheus
- name: setup node exporter
  include_tasks: "node-exporter-{{node_exporter_type}}.yml"
  when: 
    - node_exporter_enable | bool
    - node_exporter_type in ['docker', 'systemd']

- name: setup blackbox exporter
  include_tasks: "blackbox-exporter-{{blackbox_exporter_type}}.yml"
  when: 
    - blackbox_exporter_enable | bool
    - blackbox_exporter_type in ['docker', 'systemd']

- name: setup prometheus
  include_tasks: "prometheus-{{prometheus_type}}.yml"
  when:
    - prometheus_enable | bool
    - prometheus_type in ['docker', 'systemd']
- name: setup cadvisor
  include_tasks: "prometheus-{{cadvisor_type}}.yml"
  when:
    - cadvisor_enable | bool
    - cadvisor_type in ['docker', 'systemd']
